---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen 80;
      location / {
        proxy_pass http://localhost:3000;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-lab-deployment
  labels:
    app: devops-lab
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-lab
  template:
    metadata:
      labels:
        app: devops-lab
    spec:
      containers:
      - name: devops-lab
        image: jedich/devops-fundamentals-docker
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
      - name: reverse-proxy
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-configs
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-configs
        configMap:
          name: nginx-config
